//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerSet
    {
        public int AnswerId { get; set; }
        public string AnswerVarible { get; set; }
        public int QuestionQuestionId { get; set; }
    
        public virtual QuestionSet QuestionSet { get; set; }
    }
}
