//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LessonSet()
        {
            this.QuestionListLessonSet = new HashSet<QuestionListLessonSet>();
            this.TrainingProgressSet = new HashSet<TrainingProgressSet>();
        }
    
        public int LessonId { get; set; }
        public int TrainingId { get; set; }
        public int Position { get; set; }
        public string LessonName { get; set; }
        public string LessonText { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> Shape { get; set; }
        public Nullable<int> Color { get; set; }
    
        public virtual TheoryLessonSet TheoryLessonSet { get; set; }
        public virtual TrainingSet TrainingSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionListLessonSet> QuestionListLessonSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingProgressSet> TrainingProgressSet { get; set; }
    }
}
