//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionSet()
        {
            this.AnswerSet = new HashSet<AnswerSet>();
        }
    
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public int LanguageLanguageId { get; set; }
        public int QuestionTypeQuestionTypeId { get; set; }
        public int CorrectOption { get; set; }
        public int AccountAccountId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual AccountSet AccountSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerSet> AnswerSet { get; set; }
        public virtual LanguageSet LanguageSet { get; set; }
        public virtual QuestionTypeSet QuestionTypeSet { get; set; }
    }
}
