//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestSet()
        {
            this.ListQuestion = new HashSet<ListQuestion>();
        }
    
        public int TestId { get; set; }
        public string TestName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int LanguageId { get; set; }
        public int AuthorId { get; set; }
        public string Description { get; set; }
    
        public virtual AccountSet AccountSet { get; set; }
        public virtual LanguageSet LanguageSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListQuestion> ListQuestion { get; set; }
    }
}
