//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestLinkSet
    {
        public int TestLinkId { get; set; }
        public int TestId { get; set; }
        public int MethodId { get; set; }
    
        public virtual MethodSet MethodSet { get; set; }
        public virtual TestSet TestSet { get; set; }
    }
}
