//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThemeSet()
        {
            this.CommentorySet = new HashSet<CommentorySet>();
        }
    
        public int ThemeId { get; set; }
        public int AuthorId { get; set; }
        public string ThemeName { get; set; }
        public string ThemeText { get; set; }
        public int ThemePoints { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual AccountSet AccountSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentorySet> CommentorySet { get; set; }
    }
}
