//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoryLessonSet
    {
        public int TheoryId { get; set; }
        public int LessonId { get; set; }
        public string TheoryText { get; set; }
        public int Position { get; set; }
        public int CodeId { get; set; }
    
        public virtual CodeSet CodeSet { get; set; }
        public virtual LessonSet LessonSet { get; set; }
    }
}
