//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForum
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProgressSet
    {
        public int TrainingProgressId { get; set; }
        public int TrainingId { get; set; }
        public int LessonId { get; set; }
        public int AccountId { get; set; }
    
        public virtual AccountSet AccountSet { get; set; }
        public virtual LessonSet LessonSet { get; set; }
        public virtual TrainingSet TrainingSet { get; set; }
    }
}
